---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: Provision Microsoft VM from Template
    name: microsoft_template
    inherits: 
    description: 
  fields:
  - Provision:
      value: "/Infrastructure/VM/Provisioning/StateMachines/Methods/Provision"
  - CheckProvisioned:
      value: "/Infrastructure/VM/Provisioning/StateMachines/Methods/CheckProvisioned"
